/* Seed data shared by the in-memory mock and Prisma seed script. */

export type SeedUser = {
  id: string;
  handle: string;
  displayName: string;
  bio: string;
  avatarColor: string;
  followers: number;
  following: number;
};

export type SeedDrop = {
  id: string;
  authorHandle: string;
  body: string;
  createdAt: Date;
  likes: number;
  replies: number;
  reposts: number;
  tags: string[];
  embeddedCode?: { lang: string; code: string };
  parentId?: string;
};

const now = Date.now();
const minute = 60_000;
const hour = 60 * minute;
const day = 24 * hour;

export const USERS: SeedUser[] = [
  {
    avatarColor: 'from-pink-500 to-rose-600',
    bio: 'DX Engineer. Building with Next.js and React.',
    displayName: 'Aurora',
    followers: 4_911,
    following: 2,
    handle: 'aurora',
    id: 'u1',
  },
  {
    avatarColor: 'from-cyan-400 to-blue-600',
    bio: 'Backend, infra, the occasional bug hunt. Berlin.',
    displayName: 'Vex',
    followers: 8_300,
    following: 451,
    handle: 'vex',
    id: 'u2',
  },
  {
    avatarColor: 'from-violet-500 to-blue-500',
    bio: 'Design engineer. Building components and patterns.',
    displayName: 'Quill',
    followers: 4_120,
    following: 198,
    handle: 'quill',
    id: 'u3',
  },
  {
    avatarColor: 'from-sky-400 to-blue-700',
    bio: 'Staff engineer on performance. Loves a good flame graph.',
    displayName: 'Onyx',
    followers: 6_840,
    following: 540,
    handle: 'onyx',
    id: 'u4',
  },
  {
    avatarColor: 'from-blue-400 to-blue-700',
    bio: "Frontend lead. Reading source code so you don't have to.",
    displayName: 'Wren',
    followers: 2_900,
    following: 188,
    handle: 'wren',
    id: 'u5',
  },
  {
    avatarColor: 'from-teal-400 to-blue-600',
    bio: 'DX and dev tools at a small shop. Coffee enthusiast.',
    displayName: 'Cinder',
    followers: 5_330,
    following: 245,
    handle: 'cinder',
    id: 'u6',
  },
  {
    avatarColor: 'from-sky-500 to-blue-600',
    bio: 'Full-stack. Building things on the side, mostly tools.',
    displayName: 'Halo',
    followers: 1_870,
    following: 612,
    handle: 'halo',
    id: 'u7',
  },
  {
    avatarColor: 'from-indigo-400 to-blue-500',
    bio: 'CTO at a startup. Hiring is hard. Shipping is harder.',
    displayName: 'Echo',
    followers: 2_140,
    following: 410,
    handle: 'echo',
    id: 'u8',
  },
];

export const DROPS: SeedDrop[] = [
  {
    authorHandle: 'aurora',
    body: 'Just shipped a tiny site that turns my conference talk outlines into a public reading list. drop.aurora.dev — eight years of notes, finally somewhere other than my Notes app.',
    createdAt: new Date(now - 8 * minute),
    id: 'd1',
    likes: 940,
    replies: 32,
    reposts: 140,
    tags: ['shipping'],
  },
  {
    authorHandle: 'vex',
    body: "Open-sourced the dashboard kit we've been iterating on for a year. Six components, zero dependencies you don't already have. Use it, fork it, send me what you build.",
    createdAt: new Date(now - 18 * minute),
    id: 'd2',
    likes: 1_240,
    replies: 88,
    reposts: 60,
    tags: ['open-source'],
  },
  {
    authorHandle: 'wren',
    body: "A weekend project I never planned to share: a focus timer that rewards me with a song from my favorites at the end of each block. It's been on my desktop for six months. Public link in bio.",
    createdAt: new Date(now - 45 * minute),
    id: 'd3',
    likes: 1_640,
    replies: 64,
    reposts: 180,
    tags: ['side-project'],
  },
  {
    authorHandle: 'quill',
    body: 'Just launched the redesign of my portfolio Three years overdue, finally honest about what I actually do. Less hero copy, more screenshots of the work.',
    createdAt: new Date(now - 1 * hour),
    id: 'd4',
    likes: 540,
    replies: 22,
    reposts: 41,
    tags: ['design'],
  },
  {
    authorHandle: 'aurora',
    body: "Released Drop today — the demo I'll be using at React Summit next week. It's a small social network built from scratch over two weeks. Everything in this feed is real.",
    createdAt: new Date(now - 2 * hour),
    id: 'd5',
    likes: 1_980,
    replies: 110,
    reposts: 320,
    tags: ['shipping', 'reactsummit'],
  },
  {
    authorHandle: 'onyx',
    body: 'Shipped a Slack bot for our team that finds the oldest open PR every Monday and just posts it No reminders, no escalation. The PR usually gets reviewed by Tuesday.',
    createdAt: new Date(now - 3 * hour),
    id: 'd6',
    likes: 2_140,
    replies: 142,
    reposts: 410,
    tags: ['shipping'],
  },
  {
    authorHandle: 'aurora',
    body: "Preview of a thing I've been writing: a one-page guide to the patterns I keep reaching for in Next.js 16. Out next month, but the rough cut is up if you want to read along.",
    createdAt: new Date(now - 4 * hour),
    id: 'd7',
    likes: 1_540,
    replies: 64,
    reposts: 220,
    tags: ['writing'],
  },
  {
    authorHandle: 'wren',
    body: "Finally pushed v1.0 of the design tokens library we've been using internally. 200 stars overnight Did not see that coming on a Tuesday.",
    createdAt: new Date(now - 5 * hour),
    id: 'd8',
    likes: 720,
    replies: 30,
    reposts: 32,
    tags: ['open-source'],
  },
  {
    authorHandle: 'echo',
    body: "Today's small ship an RSS feed for my talks. I keep forgetting which conferences I said yes to. Now I just subscribe to myself.",
    createdAt: new Date(now - 7 * hour),
    id: 'd9',
    likes: 1_180,
    replies: 41,
    reposts: 92,
    tags: ['shipping'],
  },
  {
    authorHandle: 'cinder',
    body: "Released a CLI that scaffolds the project structure I've been arguing for in PR reviews for three years. If you've reviewed a PR from me, the answer is yes, this is the structure.",
    createdAt: new Date(now - 9 * hour),
    id: 'd10',
    likes: 612,
    replies: 28,
    reposts: 48,
    tags: ['open-source'],
  },
  {
    authorHandle: 'aurora',
    body: 'Launched a tiny landing page generator for my workshops. Pick a template, drop in the dates, deploy. Eight clicks instead of an afternoon. Felt nice.',
    createdAt: new Date(now - 11 * hour),
    id: 'd11',
    likes: 1_810,
    replies: 96,
    reposts: 340,
    tags: ['shipping'],
  },
  {
    authorHandle: 'halo',
    body: "Just shipped a side-by-side comparison view to our app Two engineers asked for it independently within a week, which I've learned is the actual signal.",
    createdAt: new Date(now - 13 * hour),
    id: 'd12',
    likes: 880,
    replies: 22,
    reposts: 64,
    tags: ['shipping'],
  },
  {
    authorHandle: 'halo',
    body: "Open-sourced the talk-prep template I use for every keynote. Markdown, a slide outline, a section for what I'm afraid to forget. Use it, fork it, give a great talk.",
    createdAt: new Date(now - 16 * hour),
    id: 'd13',
    likes: 1_320,
    replies: 47,
    reposts: 180,
    tags: ['open-source'],
  },
  {
    authorHandle: 'echo',
    body: "We launched. After eighteen months. The interview pipeline tool nobody on our team enjoyed building is live, and the recruiters love it. Sometimes that's the win.",
    createdAt: new Date(now - 19 * hour),
    id: 'd14',
    likes: 1_020,
    replies: 88,
    reposts: 96,
    tags: ['shipping'],
  },
  {
    authorHandle: 'aurora',
    body: "Pushed a long-overdue rewrite of my blog tonight. Same posts, much faster, finally on the latest framework I've been writing about. Felt good to ship something small.",
    createdAt: new Date(now - 22 * hour),
    id: 'd15',
    likes: 2_410,
    replies: 142,
    reposts: 540,
    tags: ['shipping'],
  },
  {
    authorHandle: 'quill',
    body: "Counting down to React Summit. I'll be on stage Thursday with the demo I've been quietly building in public. If you spot me, say hi — coffee is on me.",
    createdAt: new Date(now - 1 * day - 6 * hour),
    id: 'd16',
    likes: 3_810,
    replies: 320,
    reposts: 1_120,
    tags: ['reactsummit'],
  },
  {
    authorHandle: 'aurora',
    body: "Two-year retro: every project I shipped in public got me something the private ones didn't. Sometimes a job, sometimes a friend, sometimes just the next idea. Worth the awkward first post every time.",
    createdAt: new Date(now - 2 * day),
    id: 'd17',
    likes: 1_120,
    replies: 47,
    reposts: 180,
    tags: ['shipping'],
  },
  {
    authorHandle: 'wren',
    body: "Spent the weekend vibe-coding a little tool that compares my Spotify history against my partner's. Just shipped it for the two of us. Tiny audience, big smile.",
    createdAt: new Date(now - 36 * minute),
    id: 'd18',
    likes: 612,
    replies: 0,
    reposts: 14,
    tags: ['shipping'],
  },
  {
    authorHandle: 'cinder',
    body: 'Released a 90-line app that turns my voice memos into to-do items. It will never get a landing page. I use it every morning.',
    createdAt: new Date(now - 90 * minute),
    id: 'd19',
    likes: 480,
    replies: 0,
    reposts: 18,
    tags: ['shipping'],
  },
  {
    authorHandle: 'onyx',
    body: "The thing nobody tells you about shipping small: the smaller it is, the more honest it feels. The app I'm proudest of this year is 240 lines and three people use it.",
    createdAt: new Date(now - 2 * hour - 20 * minute),
    id: 'd20',
    likes: 2_140,
    replies: 0,
    reposts: 410,
    tags: ['shipping'],
  },
  {
    authorHandle: 'halo',
    body: "Drafting in public for the first time. The conference badge generator I have been threatening to build for two summers is finally a real URL. v0.1, but it's a URL.",
    createdAt: new Date(now - 3 * hour - 30 * minute),
    id: 'd21',
    likes: 360,
    replies: 0,
    reposts: 22,
    tags: ['shipping'],
  },
  {
    authorHandle: 'vex',
    body: "Built a thing this afternoon that emails me a single sentence every Sunday: what did you make this week? It's the only newsletter I subscribe to where I'm both writer and reader.",
    createdAt: new Date(now - 5 * hour),
    id: 'd22',
    likes: 720,
    replies: 0,
    reposts: 28,
    tags: ['shipping'],
  },
  {
    authorHandle: 'echo',
    body: "Vibe-coded a tiny CRM for the dog walker my building hired. Took an evening, costs $0/mo, replaces a spreadsheet that was making her stop walking Shipping doesn't need a roadmap.",
    createdAt: new Date(now - 7 * hour),
    id: 'd23',
    likes: 880,
    replies: 0,
    reposts: 42,
    tags: ['shipping'],
  },
  {
    authorHandle: 'quill',
    body: "Made a one-pager that explains my partner's job to my mom. It's the most read thing I'll ship this year. Sometimes the audience is small on purpose.",
    createdAt: new Date(now - 10 * hour),
    id: 'd24',
    likes: 540,
    replies: 0,
    reposts: 16,
    tags: ['shipping'],
  },
  {
    authorHandle: 'onyx',
    body: "Released the Sunday-night reading list I've been keeping in Notes for a year. The whole point is it doesn't grow on a schedule. I drop a link when I find one I trust.",
    createdAt: new Date(now - 14 * hour),
    id: 'd25',
    likes: 410,
    replies: 0,
    reposts: 12,
    tags: ['shipping'],
  },
  {
    authorHandle: 'aurora',
    body: 'Encouragement nobody asked for: ship the thing that has one user It teaches you more than the thing with the polished pitch deck.',
    createdAt: new Date(now - 28 * hour),
    id: 'd26',
    likes: 1_640,
    replies: 0,
    reposts: 240,
    tags: ['shipping'],
  },
  {
    authorHandle: 'vex',
    body: 'Just published `@vex/use-presence` — a tiny hook for the WebSocket presence pattern I keep rewriting on every project. One hook, no provider, no context. Install and go.',
    createdAt: new Date(now - 12 * minute),
    embeddedCode: {
      code: "const peers = usePresence('room-id')\nreturn <ul>{peers.map(p => <li key={p.id}>{p.name}</li>)}</ul>",
      lang: 'tsx',
    },
    id: 'd27',
    likes: 840,
    replies: 0,
    reposts: 64,
    tags: ['open-source'],
  },
  {
    authorHandle: 'vex',
    body: 'Releasing `create-talk-deck` — the CLI I built for prepping my React Summit keynote. Markdown slides, hot reload, one command to deploy.',
    createdAt: new Date(now - 25 * minute),
    embeddedCode: {
      code: 'npx create-talk-deck my-talk\ncd my-talk\nnpm run dev',
      lang: 'bash',
    },
    id: 'd28',
    likes: 1_240,
    replies: 0,
    reposts: 180,
    tags: ['open-source'],
  },
  {
    authorHandle: 'quill',
    body: 'Open-sourced `tokens-doctor` — a CLI that finds unused design tokens in your codebase. Cleaned up 40% of ours on the first run.',
    createdAt: new Date(now - 6 * hour),
    embeddedCode: {
      code: 'npx tokens-doctor scan ./src\nnpx tokens-doctor prune --interactive',
      lang: 'bash',
    },
    id: 'd29',
    likes: 720,
    replies: 0,
    reposts: 48,
    tags: ['open-source', 'design'],
  },
  {
    authorHandle: 'cinder',
    body: 'v2 of `react-cmd` is out. Same command palette, half the bundle, full keyboard support. Drop it into any app — works without a provider.',
    createdAt: new Date(now - 1 * hour - 30 * minute),
    embeddedCode: {
      code: "<Cmd>\n  <Cmd.Input placeholder='Search…' />\n  <Cmd.List items={results} />\n</Cmd>",
      lang: 'tsx',
    },
    id: 'd30',
    likes: 1_410,
    replies: 0,
    reposts: 220,
    tags: ['open-source'],
  },
  {
    authorHandle: 'aurora',
    body: 'Published `next-cache-recipes` — a tiny repo of cache pattern examples for Next.js 16. Per-route, per-user, mutation invalidation, all in one place.',
    createdAt: new Date(now - 12 * hour),
    embeddedCode: {
      code: "async function getDrops(handle) {\n  'use cache'\n  cacheTag(`feed-${handle}`)\n  return db.drops.byHandle(handle)\n}",
      lang: 'ts',
    },
    id: 'd31',
    likes: 2_140,
    replies: 0,
    reposts: 410,
    tags: ['open-source', 'nextjs'],
  },
  {
    authorHandle: 'onyx',
    body: "Built a tiny CLI for our team that scaffolds a new server action with the tags wired up automatically Saved everyone the 'wait, which tag do I invalidate' question.",
    createdAt: new Date(now - 16 * hour),
    embeddedCode: {
      code: 'npx @onyx/action new toggleBookmark --tag bookmarks',
      lang: 'bash',
    },
    id: 'd32',
    likes: 540,
    replies: 0,
    reposts: 38,
    tags: ['open-source'],
  },
];

export const REPLIES: SeedDrop[] = [
  {
    authorHandle: 'onyx',
    body: 'Just spent ten minutes on it — the search is fast and the notes feel like notes, not blog posts. Bookmarked.',
    createdAt: new Date(now - 12 * minute),
    id: 'r1',
    likes: 142,
    parentId: 'd1',
    replies: 4,
    reposts: 9,
    tags: [],
  },
  {
    authorHandle: 'cinder',
    body: "With 16.3 you can finally lean into per-component caching for stuff like this — turned my Notes import into a `'use cache'` function and the rest fell out.",
    createdAt: new Date(now - 8 * minute),
    id: 'r2',
    likes: 88,
    parentId: 'd1',
    replies: 1,
    reposts: 3,
    tags: [],
  },
  {
    authorHandle: 'cinder',
    body: "Cloning this tonight I have a Notes folder named 'someday' that has wanted to be a site for years.",
    createdAt: new Date(now - 4 * minute),
    id: 'r3',
    likes: 64,
    parentId: 'd1',
    replies: 0,
    reposts: 2,
    tags: [],
  },
  {
    authorHandle: 'quill',
    body: "Forking this immediately We've been about to build this kit internally for six months.",
    createdAt: new Date(now - 90 * minute),
    id: 'r4',
    likes: 220,
    parentId: 'd2',
    replies: 0,
    reposts: 18,
    tags: [],
  },
  {
    authorHandle: 'echo',
    body: "Thank you for putting a license on it. You'd be amazed how often that gets forgotten.",
    createdAt: new Date(now - 80 * minute),
    id: 'r5',
    likes: 96,
    parentId: 'd2',
    replies: 0,
    reposts: 4,
    tags: [],
  },
  {
    authorHandle: 'halo',
    body: 'A 200-star Tuesday is the dream Congrats on the v1.0 — the docs feel really cared for.',
    createdAt: new Date(now - 4 * hour),
    id: 'r6',
    likes: 312,
    parentId: 'd8',
    replies: 0,
    reposts: 22,
    tags: [],
  },
  {
    authorHandle: 'vex',
    body: 'Eight clicks is the dream. Ours takes a Google Doc, a Figma file, and a person who knows the right Slack channel.',
    createdAt: new Date(now - 10 * hour),
    id: 'r7',
    likes: 140,
    parentId: 'd11',
    replies: 0,
    reposts: 12,
    tags: [],
  },
  {
    authorHandle: 'echo',
    body: 'Counting the days. The async React talk track is the one I keep clearing my calendar for.',
    createdAt: new Date(now - 1 * day),
    id: 'r8',
    likes: 88,
    parentId: 'd16',
    replies: 0,
    reposts: 4,
    tags: ['reactsummit'],
  },
  {
    authorHandle: 'aurora',
    body: "Backstage tickets are flying — say hi if you spot the pink hoodie. The 16.3 demo is the one I'll be running live, redesign and all.",
    createdAt: new Date(now - 22 * hour),
    id: 'r9',
    likes: 140,
    parentId: 'd16',
    replies: 0,
    reposts: 12,
    tags: ['reactsummit'],
  },
  {
    authorHandle: 'wren',
    body: "Subscribed. The 'subscribe to yourself' thing is a public-talks RSS too, right? That's the kind of utility I want.",
    createdAt: new Date(now - 6 * hour),
    id: 'r10',
    likes: 64,
    parentId: 'd9',
    replies: 0,
    reposts: 2,
    tags: [],
  },
  {
    authorHandle: 'aurora',
    body: "Yes, same idea — the talks are the source, the RSS is just so I stop forgetting them. Now it's a `'use cache'` route I can subscribe to.",
    createdAt: new Date(now - 5 * hour),
    id: 'r11',
    likes: 188,
    parentId: 'd9',
    replies: 0,
    reposts: 14,
    tags: [],
  },
  {
    authorHandle: 'cinder',
    body: 'Less hero copy, more screenshots. This is the redesign brief I want to send to every team.',
    createdAt: new Date(now - 2 * hour),
    id: 'r12',
    likes: 96,
    parentId: 'd4',
    replies: 0,
    reposts: 3,
    tags: ['design'],
  },
  {
    authorHandle: 'wren',
    body: "Saved this one. The 'three years overdue' part lands — that's the entire 16.3 redesign in one sentence.",
    createdAt: new Date(now - 100 * minute),
    id: 'r13',
    likes: 220,
    parentId: 'd4',
    replies: 0,
    reposts: 18,
    tags: ['design'],
  },
  {
    authorHandle: 'halo',
    body: 'Going to read this with my morning coffee. Real ones publish the rough cut.',
    createdAt: new Date(now - 9 * hour),
    id: 'r14',
    likes: 132,
    parentId: 'd7',
    replies: 0,
    reposts: 7,
    tags: ['writing'],
  },
  {
    authorHandle: 'aurora',
    body: "Feedback welcome on the rough cut — the parts I'm least sure about are the ones I most want to fix before the print run. The 16.3 chapter is the one that keeps moving.",
    createdAt: new Date(now - 8 * hour),
    id: 'r15',
    likes: 264,
    parentId: 'd7',
    replies: 0,
    reposts: 21,
    tags: ['writing'],
  },
  {
    authorHandle: 'vex',
    body: "Two independent asks is the signal, yeah. We just shipped one of those too — the third would've been someone yelling at us.",
    createdAt: new Date(now - 14 * hour),
    id: 'r16',
    likes: 312,
    parentId: 'd12',
    replies: 0,
    reposts: 22,
    tags: [],
  },
  {
    authorHandle: 'aurora',
    body: "The 'two engineers ask independently' rule is the closest thing to a real signal in product work. Most of the 16.3 redesign came from that exact signal repeated three times.",
    createdAt: new Date(now - 13 * hour),
    id: 'r17',
    likes: 410,
    parentId: 'd12',
    replies: 0,
    reposts: 36,
    tags: [],
  },
  {
    authorHandle: 'onyx',
    body: 'Replicating Drop tonight just to have something to point my team at The shipping-to-talk pipeline is what I want to start doing.',
    createdAt: new Date(now - 18 * hour),
    id: 'r18',
    likes: 280,
    parentId: 'd5',
    replies: 0,
    reposts: 24,
    tags: ['shipping'],
  },
  {
    authorHandle: 'echo',
    body: "If you build with it, send me what you make — happy to feature stuff on stage if it's wild enough. The whole point of the 16.3 redesign was making this kind of project a weekend.",
    createdAt: new Date(now - 17 * hour),
    id: 'r19',
    likes: 188,
    parentId: 'd5',
    replies: 0,
    reposts: 14,
    tags: ['shipping'],
  },
  {
    authorHandle: 'quill',
    body: 'The PR bot is genius and shameful. We need this Will steal.',
    createdAt: new Date(now - 26 * hour),
    id: 'r20',
    likes: 220,
    parentId: 'd6',
    replies: 0,
    reposts: 18,
    tags: [],
  },
  {
    authorHandle: 'aurora',
    body: "Steal it, please. The only feature is 'oldest open PR' and that's the whole point. Now it's running on 16.3 in 40 lines.",
    createdAt: new Date(now - 25 * hour),
    id: 'r21',
    likes: 196,
    parentId: 'd6',
    replies: 0,
    reposts: 12,
    tags: [],
  },
  {
    authorHandle: 'echo',
    body: 'Have been waiting for the CLI version of your file-structure rant. It will live in my dotfiles.',
    createdAt: new Date(now - 30 * hour),
    id: 'r22',
    likes: 88,
    parentId: 'd10',
    replies: 0,
    reposts: 5,
    tags: [],
  },
  {
    authorHandle: 'halo',
    body: "Honestly should have been a CLI four years ago. The 16.3 templates it scaffolds are the ones we've been quietly converging on across every project.",
    createdAt: new Date(now - 29 * hour),
    id: 'r23',
    likes: 142,
    parentId: 'd10',
    replies: 0,
    reposts: 9,
    tags: [],
  },
  {
    authorHandle: 'aurora',
    body: 'Eight clicks beats an afternoon every time. With 16.3 the announce flow is a server action + a tagged cache — feels almost embarrassing how short it got.',
    createdAt: new Date(now - 40 * minute),
    id: 'r24',
    likes: 96,
    parentId: 'd11',
    replies: 0,
    reposts: 3,
    tags: [],
  },
  {
    authorHandle: 'aurora',
    body: "If you're using this template for a workshop too, send me a link — happy to cross-link. The 16.3 prefetch hints make these landing pages feel instant on a click.",
    createdAt: new Date(now - 30 * minute),
    id: 'r25',
    likes: 132,
    parentId: 'd11',
    replies: 0,
    reposts: 5,
    tags: [],
  },
  {
    authorHandle: 'aurora',
    body: "The two-user app is undefeated. Mine this year was a chore-rotation thing for my partner and me. 16.3's private cache made the per-user state of it disappear.",
    createdAt: new Date(now - 28 * minute),
    id: 'r26',
    likes: 220,
    parentId: 'd18',
    replies: 0,
    reposts: 18,
    tags: ['shipping'],
  },
  {
    authorHandle: 'cinder',
    body: "Selfishly shipping is so underrated. The bar moves from 'will users love it' to 'do I love it'.",
    createdAt: new Date(now - 1 * hour),
    id: 'r27',
    likes: 142,
    parentId: 'd20',
    replies: 0,
    reposts: 9,
    tags: [],
  },
  {
    authorHandle: 'vex',
    body: "240 lines, three users, one of which is your mom. That's the dream rollout.",
    createdAt: new Date(now - 90 * minute),
    id: 'r28',
    likes: 96,
    parentId: 'd20',
    replies: 0,
    reposts: 4,
    tags: [],
  },
  {
    authorHandle: 'quill',
    body: "Honestly the friction of shipping a real URL is the whole exercise. Once it's at a URL it counts. The 16.3 deploy story makes the URL step easier than the badge.",
    createdAt: new Date(now - 2 * hour),
    id: 'r29',
    likes: 188,
    parentId: 'd21',
    replies: 0,
    reposts: 12,
    tags: ['shipping'],
  },
  {
    authorHandle: 'wren',
    body: "I'd subscribe to a newsletter where the only rule is 'one sentence about what you made'.",
    createdAt: new Date(now - 4 * hour),
    id: 'r30',
    likes: 88,
    parentId: 'd22',
    replies: 0,
    reposts: 3,
    tags: [],
  },
  {
    authorHandle: 'aurora',
    body: "Replacing a spreadsheet is one of the most useful things software can do for a real person. Now imagine doing it in an evening on the 16.3 stack — that's the redesign in practice.",
    createdAt: new Date(now - 6 * hour),
    id: 'r31',
    likes: 240,
    parentId: 'd23',
    replies: 0,
    reposts: 16,
    tags: ['shipping'],
  },
  {
    authorHandle: 'halo',
    body: 'Audience-of-one apps are a vibe. Mine is a tiny pantry tracker that nags me about my chickpeas.',
    createdAt: new Date(now - 9 * hour),
    id: 'r32',
    likes: 132,
    parentId: 'd24',
    replies: 0,
    reposts: 6,
    tags: ['shipping'],
  },
  {
    authorHandle: 'onyx',
    body: "Slow-grow lists are the best lists. The pressure to publish weekly is what kills good reading. The 16.3 ISR-ish 'cache for hours' is the perfect shape for a list like this.",
    createdAt: new Date(now - 13 * hour),
    id: 'r33',
    likes: 156,
    parentId: 'd25',
    replies: 0,
    reposts: 8,
    tags: [],
  },
];

export const FOLLOWS: Record<string, string[]> = {
  aurora: ['vex', 'quill'],
  cinder: ['halo', 'echo'],
  echo: ['onyx', 'wren'],
  halo: ['cinder', 'echo'],
  onyx: ['wren', 'halo'],
  quill: ['cinder', 'onyx'],
  vex: ['aurora', 'quill'],
  wren: ['echo', 'vex'],
};

export const LIKES: Record<string, string[]> = {
  aurora: ['d2', 'd4', 'd8', 'd10'],
};

export const REPOSTS: Record<string, string[]> = {
  aurora: ['d6', 'd8'],
};

export const BOOKMARKS: Record<string, string[]> = {
  aurora: ['d2', 'd12'],
};

